### ISSUE TITLE
Add GPUs

### ISSUE THREAD

**Issue by vghiur** [akash-network/provider-configs#29]
root@node1:~# provider-services tools psutil list gpu | jq '.cards[] | .pci | {vendor: .vendor, product: .product}'
{
  "vendor": {
    "id": "1a03",
    "name": "ASPEED Technology, Inc."
  },
  "product": {
    "id": "2000",
    "name": "ASPEED Graphics Family"
  }
}
{
  "vendor": {
    "id": "10de",
    "name": "NVIDIA Corporation"
  },
  "product": {
    "id": "1db8",
    "name": "GV100GL [Tesla V100 SXM3 32GB]"
  }
}
{
  "vendor": {
    "id": "10de",
    "name": "NVIDIA Corporation"
  },
  "product": {
    "id": "1db8",
    "name": "GV100GL [Tesla V100 SXM3 32GB]"
  }
}
{
  "vendor": {
    "id": "10de",
    "name": "NVIDIA Corporation"
  },
  "product": {
    "id": "1db8",
    "name": "GV100GL [Tesla V100 SXM3 32GB]"
  }
}
{
  "vendor": {
    "id": "10de",
    "name": "NVIDIA Corporation"
  },
  "product": {
    "id": "1db8",
    "name": "GV100GL [Tesla V100 SXM3 32GB]"
  }
}
{
  "vendor": {
    "id": "10de",
    "name": "NVIDIA Corporation"
  },
  "product": {
    "id": "1db8",
    "name": "GV100GL [Tesla V100 SXM3 32GB]"
  }
}
{
  "vendor": {
    "id": "10de",
    "name": "NVIDIA Corporation"
  },
  "product": {
    "id": "1db8",
    "name": "GV100GL [Tesla V100 SXM3 32GB]"
  }
}
{
  "vendor": {
    "id": "10de",
    "name": "NVIDIA Corporation"
  },
  "product": {
    "id": "1db8",
    "name": "GV100GL [Tesla V100 SXM3 32GB]"
  }
}
{
  "vendor": {
    "id": "10de",
    "name": "NVIDIA Corporation"
  },
  "product": {
    "id": "1db8",
    "name": "GV100GL [Tesla V100 SXM3 32GB]"
  }
}
{
  "vendor": {
    "id": "10de",
    "name": "NVIDIA Corporation"
  },
  "product": {
    "id": "1db8",
    "name": "GV100GL [Tesla V100 SXM3 32GB]"
  }
}
{
  "vendor": {
    "id": "10de",
    "name": "NVIDIA Corporation"
  },
  "product": {
    "id": "1db8",
    "name": "GV100GL [Tesla V100 SXM3 32GB]"
  }
}
{
  "vendor": {
    "id": "10de",
    "name": "NVIDIA Corporation"
  },
  "product": {
    "id": "1db8",
    "name": "GV100GL [Tesla V100 SXM3 32GB]"
  }
}
{
  "vendor": {
    "id": "10de",
    "name": "NVIDIA Corporation"
  },
  "product": {
    "id": "1db8",
    "name": "GV100GL [Tesla V100 SXM3 32GB]"
  }
}
{
  "vendor": {
    "id": "10de",
    "name": "NVIDIA Corporation"
  },
  "product": {
    "id": "1db8",
    "name": "GV100GL [Tesla V100 SXM3 32GB]"
  }
}
{
  "vendor": {
    "id": "10de",
    "name": "NVIDIA Corporation"
  },
  "product": {
    "id": "1db8",
    "name": "GV100GL [Tesla V100 SXM3 32GB]"
  }
}
{
  "vendor": {
    "id": "10de",
    "name": "NVIDIA Corporation"
  },
  "product": {
    "id": "1db8",
    "name": "GV100GL [Tesla V100 SXM3 32GB]"
  }
}
{
  "vendor": {
    "id": "10de",
    "name": "NVIDIA Corporation"
  },
  "product": {
    "id": "1db8",
    "name": "GV100GL [Tesla V100 SXM3 32GB]"
  }
}
root@node1:~#

**Comment by andy108369** [comment]
This PR https://github.com/akash-network/provider-configs/pull/30 should add your GPU.
