### ISSUE TITLE
add gpus

### ISSUE THREAD

**Issue by zross5** [akash-network/provider-configs#5]
[node1.json](https://github.com/akash-network/provider-configs/files/14085366/node1.json)
[node2.json](https://github.com/akash-network/provider-configs/files/14085435/node2.json)
[node3.json](https://github.com/akash-network/provider-configs/files/14085436/node3.json)
[node4.json](https://github.com/akash-network/provider-configs/files/14085437/node4.json)
[node5.json](https://github.com/akash-network/provider-configs/files/14085439/node5.json)
[node6.json](https://github.com/akash-network/provider-configs/files/14085441/node6.json)
[node7.json](https://github.com/akash-network/provider-configs/files/14085442/node7.json)
[node8.json](https://github.com/akash-network/provider-configs/files/14085443/node8.json)

**Comment by chainzero** [comment]
JSON file has been updated with models in this issue
