### ISSUE TITLE
add gpus

### ISSUE THREAD

**Issue by nickmarkfurness** [akash-network/provider-configs#7]
{
  "cards": [
    {
      "address": "0000:12:00.0",
      "index": 0,
      "pci": {
        "driver": "ast",
        "address": "0000:12:00.0",
        "vendor": {
          "id": "1a03",
          "name": "ASPEED Technology, Inc."
        },
        "product": {
          "id": "2000",
          "name": "ASPEED Graphics Family"
        },
        "revision": "0x41",
        "subsystem": {
          "id": "0964",
          "name": "unknown"
        },
        "class": {
          "id": "03",
          "name": "Display controller"
        },
        "subclass": {
          "id": "00",
          "name": "VGA compatible controller"
        },
        "programming_interface": {
          "id": "00",
          "name": "VGA controller"
        }
      },
      "node": {
        "id": 1,
        "cores": [
          {
            "id": 10,
            "total_threads": 2,
            "logical_processors": [
              10,
              74
            ]
          },
          {
            "id": 11,
            "total_threads": 2,
            "logical_processors": [
              11,
              75
            ]
          },
          {
            "id": 12,
            "total_threads": 2,
            "logical_processors": [
              12,
              76
            ]
          },
          {
            "id": 13,
            "total_threads": 2,
            "logical_processors": [
              13,
              77
            ]
          },
          {
            "id": 14,
            "total_threads": 2,
            "logical_processors": [
              14,
              78
            ]
          },
          {
            "id": 15,
            "total_threads": 2,
            "logical_processors": [
              15,
              79
            ]
          },
          {
            "id": 8,
            "total_threads": 2,
            "logical_processors": [
              72,
              8
            ]
          },
          {
            "id": 9,
            "total_threads": 2,
            "logical_processors": [
              73,
              9
            ]
          }
        ],
        "caches": [
          {
            "level": 1,
            "type": "instruction",
            "size_bytes": 65536,
            "logical_processors": [
              8,
              72
            ]
          },
          {
            "level": 1,
            "type": "instruction",
            "size_bytes": 65536,
            "logical_processors": [
              9,
              73
            ]
          },
          {
            "level": 1,
            "type": "instruction",
            "size_bytes": 65536,
            "logical_processors": [
              10,
              74
            ]
          },
          {
            "level": 1,
            "type": "instruction",
            "size_bytes": 65536,
            "logical_processors": [
              11,
              75
            ]
          },
          {
            "level": 1,
            "type": "instruction",
            "size_bytes": 65536,
            "logical_processors": [
              12,
              76
            ]
          },
          {
            "level": 1,
            "type": "instruction",
            "size_bytes": 65536,
            "logical_processors": [
              13,
              77
            ]
          },
          {
            "level": 1,
            "type": "instruction",
            "size_bytes": 65536,
            "logical_processors": [
              14,
              78
            ]
          },
          {
            "level": 1,
            "type": "instruction",
            "size_bytes": 65536,
            "logical_processors": [
              15,
              79
            ]
          },
          {
            "level": 1,
            "type": "data",
            "size_bytes": 65536,
            "logical_processors": [
              8,
              72
            ]
          },
          {
            "level": 1,
            "type": "data",
            "size_bytes": 65536,
            "logical_processors": [
              9,
              73
            ]
          },
          {
            "level": 1,
            "type": "data",
            "size_bytes": 65536,
            "logical_processors": [
              10,
              74
            ]
          },
          {
            "level": 1,
            "type": "data",
            "size_bytes": 65536,
            "logical_processors": [
              11,
              75
            ]
          },
          {
            "level": 1,
            "type": "data",
            "size_bytes": 65536,
            "logical_processors": [
              12,
              76
            ]
          },
          {
            "level": 1,
            "type": "data",
            "size_bytes": 65536,
            "logical_processors": [
              13,
              77
            ]
          },
          {
            "level": 1,
            "type": "data",
            "size_bytes": 65536,
            "logical_processors": [
              14,
              78
            ]
          },
          {
            "level": 1,
            "type": "data",
            "size_bytes": 65536,
            "logical_processors": [
              15,
              79
            ]
          },
          {
            "level": 2,
            "type": "unified",
            "size_bytes": 524288,
            "logical_processors": [
              8,
              72
            ]
          },
          {
            "level": 2,
            "type": "unified",
            "size_bytes": 524288,
            "logical_processors": [
              9,
              73
            ]
          },
          {
            "level": 2,
            "type": "unified",
            "size_bytes": 524288,
            "logical_processors": [
              10,
              74
            ]
          },
          {
            "level": 2,
            "type": "unified",
            "size_bytes": 524288,
            "logical_processors": [
              11,
              75
            ]
          },
          {
            "level": 2,
            "type": "unified",
            "size_bytes": 524288,
            "logical_processors": [
              12,
              76
            ]
          },
          {
            "level": 2,
            "type": "unified",
            "size_bytes": 524288,
            "logical_processors": [
              13,
              77
            ]
          },
          {
            "level": 2,
            "type": "unified",
            "size_bytes": 524288,
            "logical_processors": [
              14,
              78
            ]
          },
          {
            "level": 2,
            "type": "unified",
            "size_bytes": 524288,
            "logical_processors": [
              15,
              79
            ]
          },
          {
            "level": 3,
            "type": "unified",
            "size_bytes": 8388608,
            "logical_processors": [
              8,
              9,
              10,
              11,
              72,
              73,
              74,
              75
            ]
          },
          {
            "level": 3,
            "type": "unified",
            "size_bytes": 8388608,
            "logical_processors": [
              12,
              13,
              14,
              15,
              76,
              77,
              78,
              79
            ]
          }
        ],
        "distances": [
          16,
          10,
          16,
          16,
          32,
          32,
          32,
          32
        ],
        "memory": {
          "total_physical_bytes": 70866960384,
          "total_usable_bytes": 67641008128,
          "supported_page_sizes": [
            1073741824,
            2097152
          ],
          "modules": null
        }
      }
    },
    {
      "address": "0000:21:00.0",
      "index": 1,
      "pci": {
        "driver": "nvidia",
        "address": "0000:21:00.0",
        "vendor": {
          "id": "10de",
          "name": "NVIDIA Corporation"
        },
        "product": {
          "id": "2204",
          "name": "GA102 [GeForce RTX 3090]"
        },
        "revision": "0xa1",
        "subsystem": {
          "id": "147d",
          "name": "unknown"
        },
        "class": {
          "id": "03",
          "name": "Display controller"
        },
        "subclass": {
          "id": "00",
          "name": "VGA compatible controller"
        },
        "programming_interface": {
          "id": "00",
          "name": "VGA controller"
        }
      },
      "node": {
        "id": 2,
        "cores": [
          {
            "id": 16,
            "total_threads": 2,
            "logical_processors": [
              16,
              80
            ]
          },
          {
            "id": 17,
            "total_threads": 2,
            "logical_processors": [
              17,
              81
            ]
          },
          {
            "id": 18,
            "total_threads": 2,
            "logical_processors": [
              18,
              82
            ]
          },
          {
            "id": 19,
            "total_threads": 2,
            "logical_processors": [
              19,
              83
            ]
          },
          {
            "id": 20,
            "total_threads": 2,
            "logical_processors": [
              20,
              84
            ]
          },
          {
            "id": 21,
            "total_threads": 2,
            "logical_processors": [
              21,
              85
            ]
          },
          {
            "id": 22,
            "total_threads": 2,
            "logical_processors": [
              22,
              86
            ]
          },
          {
            "id": 23,
            "total_threads": 2,
            "logical_processors": [
              23,
              87
            ]
          }
        ],
        "caches": [
          {
            "level": 1,
            "type": "instruction",
            "size_bytes": 65536,
            "logical_processors": [
              16,
              80
            ]
          },
          {
            "level": 1,
            "type": "instruction",
            "size_bytes": 65536,
            "logical_processors": [
              17,
              81
            ]
          },
          {
            "level": 1,
            "type": "instruction",
            "size_bytes": 65536,
            "logical_processors": [
              18,
              82
            ]
          },
          {
            "level": 1,
            "type": "instruction",
            "size_bytes": 65536,
            "logical_processors": [
              19,
              83
            ]
          },
          {
            "level": 1,
            "type": "instruction",
            "size_bytes": 65536,
            "logical_processors": [
              20,
              84
            ]
          },
          {
            "level": 1,
            "type": "instruction",
            "size_bytes": 65536,
            "logical_processors": [
              21,
              85
            ]
          },
          {
            "level": 1,
            "type": "instruction",
            "size_bytes": 65536,
            "logical_processors": [
              22,
              86
            ]
          },
          {
            "level": 1,
            "type": "instruction",
            "size_bytes": 65536,
            "logical_processors": [
              23,
              87
            ]
          },
          {
            "level": 1,
            "type": "data",
            "size_bytes": 65536,
            "logical_processors": [
              16,
              80
            ]
          },
          {
            "level": 1,
            "type": "data",
            "size_bytes": 65536,
            "logical_processors": [
              17,
              81
            ]
          },
          {
            "level": 1,
            "type": "data",
            "size_bytes": 65536,
            "logical_processors": [
              18,
              82
            ]
          },
          {
            "level": 1,
            "type": "data",
            "size_bytes": 65536,
            "logical_processors": [
              19,
              83
            ]
          },
          {
            "level": 1,
            "type": "data",
            "size_bytes": 65536,
            "logical_processors": [
              20,
              84
            ]
          },
          {
            "level": 1,
            "type": "data",
            "size_bytes": 65536,
            "logical_processors": [
              21,
              85
            ]
          },
          {
            "level": 1,
            "type": "data",
            "size_bytes": 65536,
            "logical_processors": [
              22,
              86
            ]
          },
          {
            "level": 1,
            "type": "data",
            "size_bytes": 65536,
            "logical_processors": [
              23,
              87
            ]
          },
          {
            "level": 2,
            "type": "unified",
            "size_bytes": 524288,
            "logical_processors": [
              16,
              80
            ]
          },
          {
            "level": 2,
            "type": "unified",
            "size_bytes": 524288,
            "logical_processors": [
              17,
              81
            ]
          },
          {
            "level": 2,
            "type": "unified",
            "size_bytes": 524288,
            "logical_processors": [
              18,
              82
            ]
          },
          {
            "level": 2,
            "type": "unified",
            "size_bytes": 524288,
            "logical_processors": [
              19,
              83
            ]
          },
          {
            "level": 2,
            "type": "unified",
            "size_bytes": 524288,
            "logical_processors": [
              20,
              84
            ]
          },
          {
            "level": 2,
            "type": "unified",
            "size_bytes": 524288,
            "logical_processors": [
              21,
              85
            ]
          },
          {
            "level": 2,
            "type": "unified",
            "size_bytes": 524288,
            "logical_processors": [
              22,
              86
            ]
          },
          {
            "level": 2,
            "type": "unified",
            "size_bytes": 524288,
            "logical_processors": [
              23,
              87
            ]
          },
          {
            "level": 3,
            "type": "unified",
            "size_bytes": 8388608,
            "logical_processors": [
              16,
              17,
              18,
              19,
              80,
              81,
              82,
              83
            ]
          },
          {
            "level": 3,
            "type": "unified",
            "size_bytes": 8388608,
            "logical_processors": [
              20,
              21,
              22,
              23,
              84,
              85,
              86,
              87
            ]
          }
        ],
        "distances": [
          16,
          16,
          10,
          16,
          32,
          32,
          32,
          32
        ],
        "memory": {
          "total_physical_bytes": 70866960384,
          "total_usable_bytes": 67641008128,
          "supported_page_sizes": [
            1073741824,
            2097152
          ],
          "modules": null
        }
      }
    }
  ]
}

**Comment by chainzero** [comment]
JSON file has been updated with the models in this files
